/* THIS FILE IS AUTOMATICALLY GENERATED */
/* DON'T MODIFY IT DIRECTLY             */
/* (unless you know what you're doing)  */

#define INIT_NURSERY_SIZE (2 * 1024 * 1024)
#define GEN0_GROW_FACTOR 0.5
#define GEN0_GROW_ADDITION (32 * 1024)
#define LOG_PAGE_SIZE 14

#include "tuning.h"
